### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by imhuy** [fa0311/TwitterInternalAPIDocument#147]
i used api, but all 403 error, can you give me any instructions. Or how can I contact you to develop the app together?

**Comment by fa0311** [comment]
This document is not complete and some parameters are missing
This is a technical issue and a limitation of static analysis

The missing parameters can be found here
https://github.com/fa0311/twitter-openapi

**Comment by fa0311** [comment]
I added this one.

https://github.com/fa0311/TwitterInternalAPIDocument/issues/148
