### ISSUE TITLE
errorfix lib/graphql.py about warning NotFoundKey: rweb_video_timestamps_enabled

### ISSUE THREAD

**Issue by TheGreatestNyanCat** [fa0311/TwitterInternalAPIDocument#391]
original source
https://github.com/fa0311/TwitterInternalAPIDocument/blob/06827acad4bdf801bc93821d8cfb024be3440f0a/lib/graphql.py#L116-L128

"rweb_video_timestamps_enabled" isn't in the feature_switch.
That key only in the feature_switch["config"].

So, I edited source code.

def marge_metadata(graphql_output: list, feature_switch: dict) -> list:
    for i in range(len(graphql_output)):
        graphql_output[i]["exports"]["metadata"]["featureSwitch"] = {}
        for switch in graphql_output[i]["exports"]["metadata"]["featureSwitches"]:
            for k in feature_switch:
                if switch == k:
                    graphql_output[i]["exports"]["metadata"]["featureSwitch"][
                        switch
                    ] = feature_switch[k]
                    break
            else:
    ### --- edited --- ###
                # logging.warning("NotFoundKey: " + switch) # deprecated
                logging.warning("(orig) NotFoundKey. trying to get from config. errorkey: " + switch)
                if "config" in feature_switch:
                    for config_k in feature_switch["config"]:
                        if switch == config_k:
                            graphql_output[i]["exports"]["metadata"]["featureSwitch"][
                                switch
                            ] = feature_switch["config"][config_k]
                            print("[>] Fixed! Key: " + switch + " / " + "Value: " + str(feature_switch["config"][config_k]))
                            break
                    else:
                        logging.warning("(edit/final) NotFoundKey: " + switch)
                else:
                    logging.warning("(edit/final) cannot find config section. NotFoundKey: " + switch)
    ### --- edited --- ###
    return graphql_output

**Comment by fa0311** [comment]
Can you send a pull request?

**Comment by TheGreatestNyanCat** [comment]
wait for moment... I try that.
It can take a long time. It is first pull requests in my github life.

**Comment by TheGreatestNyanCat** [comment]
@fa0311 I pull requests now! Check: https://github.com/fa0311/TwitterInternalAPIDocument/pull/392
